/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.moz.kuriovizor.ui;

import cz.moz.kuriovizor.daos.ItemsDao;
import cz.moz.kuriovizor.daos.UnitsDao;
import cz.moz.kuriovizor.domain.Item;
import cz.moz.kuriovizor.domain.ItemUnit;
import cz.moz.kuriovizor.domain.Unit2;
import cz.moz.kuriovizor.ui.sub.LstItemsCellRenderer;
import cz.moz.kuriovizor.ui.sub.LstItemsModel;
import cz.moz.kuriovizor.ui.sub.UnitItemsViewTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author moz
 */
public class UnitDialog extends javax.swing.JDialog {

    private Unit2 unit;
//    private StorageEntitiesDao storeDao;
    private UnitsDao unitsDao;
    private ItemsDao itemsDao;
    
    private List<ItemUnit> itemsToDelete;

    public Unit2 getUnit() {
        if (this.unit == null) {
            this.unit = new Unit2();
        }
        return unit;
    }

    public void setUnit(Unit2 unit) {
        this.unit = unit;
    }

    public List<ItemUnit> getItemsToDelete() {
        if(itemsToDelete == null)
            itemsToDelete = new ArrayList<>();
        return itemsToDelete;
    }
    
//    public void setStoreDao(StorageEntitiesDao storeDao) {
//        this.storeDao = storeDao;
//    }
    public void setUnitsDao(UnitsDao unitsDao) {
        this.unitsDao = unitsDao;
    }

    public void setItemsDao(ItemsDao itemsDao) {
        this.itemsDao = itemsDao;
    }

    /**
     * Creates new form UnitDialog
     */
    public UnitDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void initData() {
        txtId.setText(String.valueOf(getUnit().getId()));
        txtName.setText(getUnit().getUnitName());
        txtCode.setText(getUnit().getCode());

//        StoreEntriesListModel model = new StoreEntriesListModel();
//        model.setList(this.storeDao.getAllEntities());
//        lstItems.setModel(model);
//        
//        List<ItemUnit> unitItemsList = new ArrayList<ItemUnit>();
//        unitItemsList.addAll(getUnit().getItems());
//        getUnit().getItems()
//        UnitItemsListModel unitItemsModel = new UnitItemsListModel();
//        unitItemsModel.setList(unitItemsList);
//        StoreEntriesListModel model2 = new StoreEntriesListModel();
//        model2.setList(unitItemsModel);
//        lstItems.setModel(unitItemsModel);
        refreshTblUnitItems();

        LstItemsModel lstItemsModel = new LstItemsModel();
        lstItemsModel.setList(this.itemsDao.getAllItems());
        lstItems.setModel(lstItemsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JFormattedTextField();
        txtName = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        addItemUnit = new javax.swing.JButton();
        btnDeleteItemUnit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEditCount = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUnitItems = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id:");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 14));

        jLabel2.setText("Name:");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 14));

        jLabel3.setText("Code:");
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 14));

        txtId.setText("jFormattedTextField1");
        txtId.setPreferredSize(new java.awt.Dimension(200, 29));

        txtName.setPreferredSize(new java.awt.Dimension(200, 29));

        txtCode.setPreferredSize(new java.awt.Dimension(200, 29));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Entities from storage"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        lstItems.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstItems.setCellRenderer(new LstItemsCellRenderer());
        jScrollPane1.setViewportView(lstItems);

        jPanel3.add(jScrollPane1);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        addItemUnit.setText(">");
        addItemUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemUnitActionPerformed(evt);
            }
        });

        btnDeleteItemUnit.setText("<");
        btnDeleteItemUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemUnitActionPerformed(evt);
            }
        });

        jButton3.setText("clear");

        btnEditCount.setText("Edit count");
        btnEditCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(btnDeleteItemUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addItemUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItemUnit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteItemUnit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditCount))
        );

        jPanel5.add(jPanel6, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel5);

        tblUnitItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Required count"
            }
        ));
        jScrollPane2.setViewportView(tblUnitItems);

        jPanel3.add(jScrollPane2);

        jButton4.setText("Cancel");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 249, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(btnSave))
                .addGap(6, 6, 6))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Items from storage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCountActionPerformed
        int index = tblUnitItems.convertRowIndexToModel(tblUnitItems.getSelectedRow());
        if (index == - 1) {
            System.out.println("Nebyl vybran zadny prvek.");
        } else {
            ItemUnit entity = getUnit().getItems().get(index);
            String str = JOptionPane.showInputDialog(this, "Pocet: ", "", 1);
            Integer newCount = Integer.valueOf(str);
            System.out.println("Novy pocet je: " + str);
            entity.setRequiredCount(newCount);
            unitsDao.updateItemUnit(entity);
            System.out.println("Jednotka byla ulozena");
            refreshTblUnitItems();
        }
    }//GEN-LAST:event_btnEditCountActionPerformed
    
    private void addItemUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemUnitActionPerformed
        // Ulozeni se projevi az po stisknuti tlacitka save.
        
        System.out.println("selected: " + lstItems.getSelectedIndex());
        if (lstItems.getSelectedIndex() != -1) {
            if (lstItems.getSelectedValue() instanceof Item) {
                String count = JOptionPane.showInputDialog(this, "Required count: ", "Required count of items");
                if (count != null) {
                    ItemUnit itemUnit = new ItemUnit();
                    itemUnit.setItem((Item) lstItems.getSelectedValue());
                    itemUnit.setUnit(getUnit());
                    itemUnit.setRequiredCount(Integer.valueOf(count));
                    getUnit().getItems().add(itemUnit);
                    refreshTblUnitItems();
                }

            }
        }
    }//GEN-LAST:event_addItemUnitActionPerformed

    private void refreshTblUnitItems() {
        UnitItemsViewTableModel unitItemsViewTableModel = new UnitItemsViewTableModel();
        unitItemsViewTableModel.setList(getUnit().getItems());
        tblUnitItems.setModel(unitItemsViewTableModel);
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        for (ItemUnit itemUnit : getUnit().getItems()) {
            unitsDao.saveItemUnit(itemUnit);
        }
        for(ItemUnit itemUnit : getItemsToDelete()) {
            unitsDao.deleteItemUnit(itemUnit);
        }
        unitsDao.saveUnit(this.getUnit());
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteItemUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemUnitActionPerformed
        int index = tblUnitItems.convertRowIndexToModel(tblUnitItems.getSelectedRow());
        if (index == -1) {
            System.out.println("Nebyl vybran zadny prvek.");
        } else {
            ItemUnit itemUnit = getUnit().getItems().get(index);
            getItemsToDelete().add(itemUnit);
//            unitsDao.deleteItemUnit(itemUnit);
            getUnit().getItems().remove(itemUnit);
            refreshTblUnitItems();
        }
    }//GEN-LAST:event_btnDeleteItemUnitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnitDialog dialog = new UnitDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemUnit;
    private javax.swing.JButton btnDeleteItemUnit;
    private javax.swing.JButton btnEditCount;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstItems;
    private javax.swing.JTable tblUnitItems;
    private javax.swing.JTextField txtCode;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
