drop table storage if exists;
create table storage(
    id int generated by default as identity(start with 1) unique,
    company varchar(40),
    product_Name varchar(70),
    quantity integer default 0,
    min_count integer default 0,
    code varchar(20),
    delivery integer,
    price float default 0.0,
    primary key(id)
);

drop table units if exists cascade;
create table units(
    id int generated by default as identity(start with 1) unique,
    unit_name varchar(30),
    code varchar(25)
);

drop table units_entities if exists cascade;
create table units_entities(
    id int generated by default as identity(start with 1),
    unit_id int,
    storage_id int,
    required_count int,
    foreign key (unit_id) references units(id),
    foreign key (storage_id) references storage(id)
);

insert into storage (product_name, quantity, code, price) values ('Rám DHW', 11, 'AX315', 55.60);
insert into storage (product_name, quantity, price) values ('Pravý boční kryt', 54, 100);
insert into storage (product_name, quantity, price) values ('Levý boční kryt', 54, 78.50);
insert into storage (product_name, quantity, price) values ('Zadní kryt', 54, 12.20);
insert into storage (product_name, quantity, price) values ('Horní kryt', 54, 33.60);
insert into storage (product_name, quantity) values ('Přední dveře', 54);

select * from storage;